### ISSUE TITLE
Network host create net-alias

### ISSUE THREAD

**Issue by eliecharra** [kibatic/docker-systemd#3]
Docker does not allow setup net alias on container running with `--network=host`

```
/usr/bin/docker: Error response from daemon: network-scoped alias is supported only for containers in user defined networks.
```

Unit are not starting for a following setup :

```yaml
systemd_units:
  - name: nginx-proxy
    image: nginx:1.11
    network: host
```
